-- Enrich IMAGE layout: free rotation, scaleX/Y, offsets, crop shape, background
ALTER TABLE "Media" ALTER COLUMN "rotation" TYPE DOUBLE PRECISION USING "rotation"::double precision;

ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "offsetX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "offsetY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "scaleX" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "scaleY" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "lockAspect" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "cropShape" TEXT NOT NULL DEFAULT 'RECT';
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "backgroundColor" TEXT NOT NULL DEFAULT '#000000';
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "cropInset" DOUBLE PRECISION NOT NULL DEFAULT 0.06;
